from PyQt5 import QtWidgets
from view import training_window
import values

class TrainingController():
    def __init__(self):
        self.trainingWindow = QtWidgets.QMainWindow()
        self.trainingWindowContent = training_window.Ui_trainingWindow()
        self.trainingWindowContent.setupUi(self.trainingWindow)
        self.trainingWindowContent.tableWidget.setItem(0, 0, QtWidgets.QTableWidgetItem("Max horizontal resolution"))
        self.trainingWindowContent.tableWidget.setItem(0, 1, QtWidgets.QTableWidgetItem("Memory technology"))
        self.trainingWindowContent.tableWidget.setItem(0, 2, QtWidgets.QTableWidgetItem("Installed memory"))
        self.trainingWindowContent.tableWidget.setItem(0, 3, QtWidgets.QTableWidgetItem("Processor speed"))
        self.trainingWindowContent.tableWidget.setItem(0, 4, QtWidgets.QTableWidgetItem("Processor"))
        self.trainingWindowContent.tableWidget.setItem(0, 5, QtWidgets.QTableWidgetItem("Manufacturer"))
        self.trainingWindowContent.tableWidget.setItem(0, 6, QtWidgets.QTableWidgetItem("Infrared"))
        self.trainingWindowContent.tableWidget.setItem(0, 7, QtWidgets.QTableWidgetItem("Bluetooth"))
        self.trainingWindowContent.tableWidget.setItem(0, 8, QtWidgets.QTableWidgetItem("Docking station"))
        self.trainingWindowContent.tableWidget.setItem(0, 9, QtWidgets.QTableWidgetItem("Port replicator"))
        self.trainingWindowContent.tableWidget.setItem(0, 10, QtWidgets.QTableWidgetItem("Fingerprint"))
        self.trainingWindowContent.tableWidget.setItem(0, 11, QtWidgets.QTableWidgetItem("Subwoofer"))
        self.trainingWindowContent.tableWidget.setItem(0, 12, QtWidgets.QTableWidgetItem("External battery"))
        self.trainingWindowContent.tableWidget.setItem(0, 13, QtWidgets.QTableWidgetItem("Operating system"))
        self.trainingWindowContent.tableWidget.setItem(0, 14, QtWidgets.QTableWidgetItem("Warranty days"))
        self.trainingWindowContent.tableWidget.setItem(0, 15, QtWidgets.QTableWidgetItem("Price"))
        self.trainingWindowContent.normalizedTableWidget.setItem(0, 0, QtWidgets.QTableWidgetItem("Max horizontal resolution"))
        self.trainingWindowContent.normalizedTableWidget.setItem(0, 1, QtWidgets.QTableWidgetItem("Memory technology"))
        self.trainingWindowContent.normalizedTableWidget.setItem(0, 2, QtWidgets.QTableWidgetItem("Installed memory"))
        self.trainingWindowContent.normalizedTableWidget.setItem(0, 3, QtWidgets.QTableWidgetItem("Processor speed"))
        self.trainingWindowContent.normalizedTableWidget.setItem(0, 4, QtWidgets.QTableWidgetItem("Processor"))
        self.trainingWindowContent.normalizedTableWidget.setItem(0, 5, QtWidgets.QTableWidgetItem("Manufacturer"))
        self.trainingWindowContent.normalizedTableWidget.setItem(0, 6, QtWidgets.QTableWidgetItem("Infrared"))
        self.trainingWindowContent.normalizedTableWidget.setItem(0, 7, QtWidgets.QTableWidgetItem("Bluetooth"))
        self.trainingWindowContent.normalizedTableWidget.setItem(0, 8, QtWidgets.QTableWidgetItem("Docking station"))
        self.trainingWindowContent.normalizedTableWidget.setItem(0, 9, QtWidgets.QTableWidgetItem("Port replicator"))
        self.trainingWindowContent.normalizedTableWidget.setItem(0, 10, QtWidgets.QTableWidgetItem("Fingerprint"))
        self.trainingWindowContent.normalizedTableWidget.setItem(0, 11, QtWidgets.QTableWidgetItem("Subwoofer"))
        self.trainingWindowContent.normalizedTableWidget.setItem(0, 12, QtWidgets.QTableWidgetItem("External battery"))
        self.trainingWindowContent.normalizedTableWidget.setItem(0, 13, QtWidgets.QTableWidgetItem("Operating system"))
        self.trainingWindowContent.normalizedTableWidget.setItem(0, 14, QtWidgets.QTableWidgetItem("Warranty days"))
        self.trainingWindowContent.normalizedTableWidget.setItem(0, 15, QtWidgets.QTableWidgetItem("Price"))