# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'config_layers.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ConfigWindow(object):
    def setupUi(self, ConfigWindow):
        ConfigWindow.setObjectName("ConfigWindow")
        ConfigWindow.resize(295, 473)
        self.centralwidget = QtWidgets.QWidget(ConfigWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.il_label = QtWidgets.QLabel(self.centralwidget)
        self.il_label.setGeometry(QtCore.QRect(10, 10, 131, 31))
        self.il_label.setObjectName("il_label")
        self.il_neurons_sb = QtWidgets.QSpinBox(self.centralwidget)
        self.il_neurons_sb.setGeometry(QtCore.QRect(220, 10, 52, 32))
        self.il_neurons_sb.setMinimum(1)
        self.il_neurons_sb.setMaximum(500)
        self.il_neurons_sb.setObjectName("il_neurons_sb")
        self.hl_title_label = QtWidgets.QLabel(self.centralwidget)
        self.hl_title_label.setGeometry(QtCore.QRect(10, 60, 101, 31))
        self.hl_title_label.setObjectName("hl_title_label")
        self.hl1_label = QtWidgets.QLabel(self.centralwidget)
        self.hl1_label.setGeometry(QtCore.QRect(60, 100, 161, 31))
        self.hl1_label.setObjectName("hl1_label")
        self.hl2_label = QtWidgets.QLabel(self.centralwidget)
        self.hl2_label.setGeometry(QtCore.QRect(60, 150, 161, 31))
        self.hl2_label.setObjectName("hl2_label")
        self.hl3_label = QtWidgets.QLabel(self.centralwidget)
        self.hl3_label.setGeometry(QtCore.QRect(60, 200, 161, 31))
        self.hl3_label.setObjectName("hl3_label")
        self.hl1_neurons_sb = QtWidgets.QSpinBox(self.centralwidget)
        self.hl1_neurons_sb.setGeometry(QtCore.QRect(220, 100, 52, 32))
        self.hl1_neurons_sb.setMinimum(1)
        self.hl1_neurons_sb.setMaximum(500)
        self.hl1_neurons_sb.setObjectName("hl1_neurons_sb")
        self.hl2_cb = QtWidgets.QCheckBox(self.centralwidget)
        self.hl2_cb.setGeometry(QtCore.QRect(30, 150, 31, 31))
        self.hl2_cb.setText("")
        self.hl2_cb.setObjectName("hl2_cb")
        self.hl2_neurons_sb = QtWidgets.QSpinBox(self.centralwidget)
        self.hl2_neurons_sb.setEnabled(False)
        self.hl2_neurons_sb.setGeometry(QtCore.QRect(220, 150, 52, 32))
        self.hl2_neurons_sb.setMinimum(1)
        self.hl2_neurons_sb.setMaximum(500)
        self.hl2_neurons_sb.setObjectName("hl2_neurons_sb")
        self.hl3_cb = QtWidgets.QCheckBox(self.centralwidget)
        self.hl3_cb.setEnabled(False)
        self.hl3_cb.setGeometry(QtCore.QRect(30, 200, 31, 31))
        self.hl3_cb.setText("")
        self.hl3_cb.setObjectName("hl3_cb")
        self.hl3_neurons_sb = QtWidgets.QSpinBox(self.centralwidget)
        self.hl3_neurons_sb.setEnabled(False)
        self.hl3_neurons_sb.setGeometry(QtCore.QRect(220, 200, 52, 32))
        self.hl3_neurons_sb.setMinimum(1)
        self.hl3_neurons_sb.setMaximum(500)
        self.hl3_neurons_sb.setObjectName("hl3_neurons_sb")
        self.ol_label = QtWidgets.QLabel(self.centralwidget)
        self.ol_label.setGeometry(QtCore.QRect(10, 260, 161, 31))
        self.ol_label.setObjectName("ol_label")
        self.ol_neurons_sb = QtWidgets.QSpinBox(self.centralwidget)
        self.ol_neurons_sb.setGeometry(QtCore.QRect(220, 260, 52, 32))
        self.ol_neurons_sb.setMinimum(1)
        self.ol_neurons_sb.setMaximum(500)
        self.ol_neurons_sb.setObjectName("ol_neurons_sb")
        self.ok_button = QtWidgets.QPushButton(self.centralwidget)
        self.ok_button.setGeometry(QtCore.QRect(10, 330, 261, 81))
        self.ok_button.setObjectName("ok_button")
        ConfigWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(ConfigWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 295, 30))
        self.menubar.setObjectName("menubar")
        ConfigWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(ConfigWindow)
        self.statusbar.setObjectName("statusbar")
        ConfigWindow.setStatusBar(self.statusbar)

        self.retranslateUi(ConfigWindow)
        QtCore.QMetaObject.connectSlotsByName(ConfigWindow)

    def retranslateUi(self, ConfigWindow):
        _translate = QtCore.QCoreApplication.translate
        ConfigWindow.setWindowTitle(_translate("ConfigWindow", "Configure layers"))
        self.il_label.setText(_translate("ConfigWindow", "Input layer neurons:"))
        self.hl_title_label.setText(_translate("ConfigWindow", "Hidden layers:"))
        self.hl1_label.setText(_translate("ConfigWindow", "Hidden layer 1 neurons:"))
        self.hl2_label.setText(_translate("ConfigWindow", "Hidden layer 2 neurons:"))
        self.hl3_label.setText(_translate("ConfigWindow", "Hidden layer 3 neurons:"))
        self.ol_label.setText(_translate("ConfigWindow", "Output layer neurons:"))
        self.ok_button.setText(_translate("ConfigWindow", "OK"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ConfigWindow = QtWidgets.QMainWindow()
    ui = Ui_ConfigWindow()
    ui.setupUi(ConfigWindow)
    ConfigWindow.show()
    sys.exit(app.exec_())
