# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'edit_input_layer.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_EditInputLayerWindow(object):
    def setupUi(self, EditInputLayerWindow):
        EditInputLayerWindow.setObjectName("EditInputLayerWindow")
        EditInputLayerWindow.resize(372, 702)
        self.centralwidget = QtWidgets.QWidget(EditInputLayerWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.title_label = QtWidgets.QLabel(self.centralwidget)
        self.title_label.setGeometry(QtCore.QRect(10, 10, 251, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.title_label.setFont(font)
        self.title_label.setObjectName("title_label")
        self.neuron_name = QtWidgets.QLabel(self.centralwidget)
        self.neuron_name.setGeometry(QtCore.QRect(280, 10, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.neuron_name.setFont(font)
        self.neuron_name.setObjectName("neuron_name")
        self.value_label = QtWidgets.QLabel(self.centralwidget)
        self.value_label.setGeometry(QtCore.QRect(10, 60, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.value_label.setFont(font)
        self.value_label.setObjectName("value_label")
        self.value_sb = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.value_sb.setGeometry(QtCore.QRect(70, 60, 91, 32))
        self.value_sb.setMaximum(999.99)
        self.value_sb.setObjectName("value_sb")
        self.sinaptics_label = QtWidgets.QLabel(self.centralwidget)
        self.sinaptics_label.setGeometry(QtCore.QRect(10, 110, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.sinaptics_label.setFont(font)
        self.sinaptics_label.setObjectName("sinaptics_label")
        self.sinaptics_listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.sinaptics_listWidget.setGeometry(QtCore.QRect(10, 140, 241, 401))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.sinaptics_listWidget.setFont(font)
        self.sinaptics_listWidget.setObjectName("sinaptics_listWidget")
        self.okButton = QtWidgets.QPushButton(self.centralwidget)
        self.okButton.setGeometry(QtCore.QRect(10, 550, 241, 81))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.okButton.setFont(font)
        self.okButton.setObjectName("okButton")
        EditInputLayerWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(EditInputLayerWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 372, 30))
        self.menubar.setObjectName("menubar")
        EditInputLayerWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(EditInputLayerWindow)
        self.statusbar.setObjectName("statusbar")
        EditInputLayerWindow.setStatusBar(self.statusbar)

        self.retranslateUi(EditInputLayerWindow)
        QtCore.QMetaObject.connectSlotsByName(EditInputLayerWindow)

    def retranslateUi(self, EditInputLayerWindow):
        _translate = QtCore.QCoreApplication.translate
        EditInputLayerWindow.setWindowTitle(_translate("EditInputLayerWindow", "Edit input layer neuron"))
        self.title_label.setText(_translate("EditInputLayerWindow", "Edit input layer neuron:"))
        self.neuron_name.setText(_translate("EditInputLayerWindow", "IL-12"))
        self.value_label.setText(_translate("EditInputLayerWindow", "Value:"))
        self.sinaptics_label.setText(_translate("EditInputLayerWindow", "Synaptic links to:"))
        self.okButton.setText(_translate("EditInputLayerWindow", "OK"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    EditInputLayerWindow = QtWidgets.QMainWindow()
    ui = Ui_EditInputLayerWindow()
    ui.setupUi(EditInputLayerWindow)
    EditInputLayerWindow.show()
    sys.exit(app.exec_())
