# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'edit_input_layer_link.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_EditInputLayerLinkWindow(object):
    def setupUi(self, EditInputLayerLinkWindow):
        EditInputLayerLinkWindow.setObjectName("EditInputLayerLinkWindow")
        EditInputLayerLinkWindow.resize(223, 347)
        self.centralwidget = QtWidgets.QWidget(EditInputLayerLinkWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.title_label = QtWidgets.QLabel(self.centralwidget)
        self.title_label.setGeometry(QtCore.QRect(10, 10, 191, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.title_label.setFont(font)
        self.title_label.setObjectName("title_label")
        self.from_label = QtWidgets.QLabel(self.centralwidget)
        self.from_label.setGeometry(QtCore.QRect(10, 70, 81, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.from_label.setFont(font)
        self.from_label.setObjectName("from_label")
        self.to_label = QtWidgets.QLabel(self.centralwidget)
        self.to_label.setGeometry(QtCore.QRect(10, 130, 81, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.to_label.setFont(font)
        self.to_label.setObjectName("to_label")
        self.value_label = QtWidgets.QLabel(self.centralwidget)
        self.value_label.setGeometry(QtCore.QRect(10, 200, 81, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.value_label.setFont(font)
        self.value_label.setObjectName("value_label")
        self.value_sb = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.value_sb.setGeometry(QtCore.QRect(100, 210, 71, 32))
        self.value_sb.setObjectName("value_sb")
        self.from_value_label = QtWidgets.QLabel(self.centralwidget)
        self.from_value_label.setGeometry(QtCore.QRect(100, 80, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.from_value_label.setFont(font)
        self.from_value_label.setObjectName("from_value_label")
        self.to_value_label = QtWidgets.QLabel(self.centralwidget)
        self.to_value_label.setGeometry(QtCore.QRect(100, 140, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.to_value_label.setFont(font)
        self.to_value_label.setObjectName("to_value_label")
        self.ok_button = QtWidgets.QPushButton(self.centralwidget)
        self.ok_button.setGeometry(QtCore.QRect(70, 260, 88, 34))
        self.ok_button.setObjectName("ok_button")
        EditInputLayerLinkWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(EditInputLayerLinkWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 223, 30))
        self.menubar.setObjectName("menubar")
        EditInputLayerLinkWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(EditInputLayerLinkWindow)
        self.statusbar.setObjectName("statusbar")
        EditInputLayerLinkWindow.setStatusBar(self.statusbar)

        self.retranslateUi(EditInputLayerLinkWindow)
        QtCore.QMetaObject.connectSlotsByName(EditInputLayerLinkWindow)

    def retranslateUi(self, EditInputLayerLinkWindow):
        _translate = QtCore.QCoreApplication.translate
        EditInputLayerLinkWindow.setWindowTitle(_translate("EditInputLayerLinkWindow", "Edit link"))
        self.title_label.setText(_translate("EditInputLayerLinkWindow", "Edit link"))
        self.from_label.setText(_translate("EditInputLayerLinkWindow", "From:"))
        self.to_label.setText(_translate("EditInputLayerLinkWindow", "To:"))
        self.value_label.setText(_translate("EditInputLayerLinkWindow", "Value:"))
        self.from_value_label.setText(_translate("EditInputLayerLinkWindow", "IL-1"))
        self.to_value_label.setText(_translate("EditInputLayerLinkWindow", "HL1-2"))
        self.ok_button.setText(_translate("EditInputLayerLinkWindow", "OK"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    EditInputLayerLinkWindow = QtWidgets.QMainWindow()
    ui = Ui_EditInputLayerLinkWindow()
    ui.setupUi(EditInputLayerLinkWindow)
    EditInputLayerLinkWindow.show()
    sys.exit(app.exec_())
