# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'visualize_layers.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_VisualizeWindow(object):
    def setupUi(self, VisualizeWindow):
        VisualizeWindow.setObjectName("VisualizeWindow")
        VisualizeWindow.resize(1525, 736)
        self.centralwidget = QtWidgets.QWidget(VisualizeWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.il_label = QtWidgets.QLabel(self.centralwidget)
        self.il_label.setGeometry(QtCore.QRect(20, 10, 131, 31))
        self.il_label.setObjectName("il_label")
        self.input_listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.input_listWidget.setGeometry(QtCore.QRect(20, 40, 291, 641))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.input_listWidget.setFont(font)
        self.input_listWidget.setObjectName("input_listWidget")
        self.hl1_label = QtWidgets.QLabel(self.centralwidget)
        self.hl1_label.setGeometry(QtCore.QRect(330, 20, 121, 16))
        self.hl1_label.setObjectName("hl1_label")
        self.hl1_listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.hl1_listWidget.setGeometry(QtCore.QRect(320, 40, 291, 641))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.hl1_listWidget.setFont(font)
        self.hl1_listWidget.setObjectName("hl1_listWidget")
        self.hl2_listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.hl2_listWidget.setGeometry(QtCore.QRect(620, 40, 291, 641))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.hl2_listWidget.setFont(font)
        self.hl2_listWidget.setObjectName("hl2_listWidget")
        self.hl2_label = QtWidgets.QLabel(self.centralwidget)
        self.hl2_label.setGeometry(QtCore.QRect(630, 20, 121, 16))
        self.hl2_label.setObjectName("hl2_label")
        self.hl3_listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.hl3_listWidget.setGeometry(QtCore.QRect(920, 40, 291, 641))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.hl3_listWidget.setFont(font)
        self.hl3_listWidget.setObjectName("hl3_listWidget")
        self.hl3_label = QtWidgets.QLabel(self.centralwidget)
        self.hl3_label.setGeometry(QtCore.QRect(930, 20, 121, 16))
        self.hl3_label.setObjectName("hl3_label")
        self.output_listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.output_listWidget.setGeometry(QtCore.QRect(1220, 40, 291, 641))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.output_listWidget.setFont(font)
        self.output_listWidget.setObjectName("output_listWidget")
        self.output_label = QtWidgets.QLabel(self.centralwidget)
        self.output_label.setGeometry(QtCore.QRect(1230, 20, 121, 16))
        self.output_label.setObjectName("output_label")
        VisualizeWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(VisualizeWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1525, 30))
        self.menubar.setObjectName("menubar")
        VisualizeWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(VisualizeWindow)
        self.statusbar.setObjectName("statusbar")
        VisualizeWindow.setStatusBar(self.statusbar)

        self.retranslateUi(VisualizeWindow)
        QtCore.QMetaObject.connectSlotsByName(VisualizeWindow)

    def retranslateUi(self, VisualizeWindow):
        _translate = QtCore.QCoreApplication.translate
        VisualizeWindow.setWindowTitle(_translate("VisualizeWindow", "Visualize network"))
        self.il_label.setText(_translate("VisualizeWindow", "Input layer:"))
        self.hl1_label.setText(_translate("VisualizeWindow", "Hidden layer 1:"))
        self.hl2_label.setText(_translate("VisualizeWindow", "Hidden layer 2:"))
        self.hl3_label.setText(_translate("VisualizeWindow", "Hidden layer 3:"))
        self.output_label.setText(_translate("VisualizeWindow", "Output layer:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    VisualizeWindow = QtWidgets.QMainWindow()
    ui = Ui_VisualizeWindow()
    ui.setupUi(VisualizeWindow)
    VisualizeWindow.show()
    sys.exit(app.exec_())
